# Generated by Django 4.2.7 on 2023-11-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Product<django.db.models.fields.CharField>')),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='categoriesmaster',
            name='slug',
            field=models.SlugField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
