# Generated by Django 4.2.7 on 2023-11-25 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaStore', '0002_productmaster_categoriesmaster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PizzaStore.categoriesmaster'),
            preserve_default=False,
        ),
    ]
