# Generated by Django 4.2.7 on 2023-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaStore', '0003_productmaster_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Socialmedia')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image',
            field=models.ImageField(upload_to='Product'),
        ),
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('contactnumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('openinghours', models.CharField(max_length=50)),
                ('copyright', models.CharField(max_length=50)),
                ('distributedby', models.CharField(max_length=20)),
                ('socialmedia', models.ManyToManyField(related_name='about', to='PizzaStore.social')),
            ],
        ),
    ]
