# Generated by Django 4.2.7 on 2023-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaStore', '0004_social_alter_productmaster_image_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest')], default='facebook'),
        ),
    ]
