# Generated by Django 4.2.7 on 2023-11-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaStore', '0005_social_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='img',
        ),
    ]
