# Generated by Django 4.2.7 on 2023-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaStore', '0009_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
