# Generated by Django 4.2.7 on 2023-11-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaStore', '0010_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymenstatus',
        ),
    ]
