# Generated by Django 4.2.7 on 2023-11-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmaster',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='User-profile'),
        ),
    ]
