# Generated by Django 4.2.7 on 2023-11-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_userauthmaster_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmaster',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Userprofile'),
        ),
    ]
