# Generated by Django 4.2.7 on 2023-12-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_alter_userauthmaster_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmaster',
            name='forgot_token',
            field=models.CharField(default='', editable=False),
        ),
    ]
