# Generated by Django 4.2.7 on 2023-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_userauthmaster_forgot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmaster',
            name='forgot_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
