# Generated by Django 4.2.7 on 2023-12-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_userauthmaster_forgot_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmaster',
            name='forgot_token_expiration',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
